version: '3.8'
services:
  container1:
    build:
      context: ./container1
    image: 'container1:latest'
  container2:
    build:
      context:  ./container2
    image: 'container2:latest'
  nginx:
    restart: always
    build:
      context: ./nginx
    image: 'nginx-custom:latest'
    ports:
      - 80:8080
    depends_on:
      - container1
      - container2